-- Add SoLuongDuKien column to HocPhan table
ALTER TABLE HocPhan ADD SoLuongDuKien INT DEFAULT 0;

-- Create tables if they don't exist
CREATE TABLE IF NOT EXISTS HocPhan (
    MaHP VARCHAR(6) PRIMARY KEY,
    TenHP VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL,
    SoTinChi INT NOT NULL,
    SoLuongDuKien INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS DangKy (
    MaDK INT AUTO_INCREMENT PRIMARY KEY,
    NgayDK DATE,
    MaSV VARCHAR(10),
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ChiTietDangKy (
    MaDK INT,
    MaHP VARCHAR(6),
    PRIMARY KEY (MaDK, MaHP),
    FOREIGN KEY (MaDK) REFERENCES DangKy(MaDK) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaHP) REFERENCES HocPhan(MaHP) ON DELETE CASCADE ON UPDATE CASCADE
); 